CREATE OR REPLACE FUNCTION VALIDAR_CEDULA(P_CI IN interesado.ci%TYPE)
RETURN VARCHAR2
IS
CANT_POSTULANTES NUMBER :=0;
BEGIN 
    SELECT COUNT(*) INTO CANT_POSTULANTES FROM POSTULACION WHERE CI=P_CI;
    
    RETURN CANT_POSTULANTES;
END;

CREATE OR REPLACE PROCEDURE MAS_POSTULACIONES
IS
CANT_POSTULANTES NUMBER :=0;
BEGIN 
    SELECT MAX FROM (SELECT ci, COUNT(*) FROM POSTULACION GROUP BY POSTULACION.ci);
    
    RETURN CANT_POSTULANTES;
END;

SELECT ci, COUNT(*) as MAX_POSTULADOR FROM POSTULACION GROUP BY POSTULACION.ci;



SELECT VALIDAR_CEDULA(5) FROM DUAL;